# application / test or tools code directories
code-directories:
  - src
  - src/lib
  - test/lib
  - tools

# appengine libraries
libraries:
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"
- name: webapp2
  version: "2.5.2"
